aws_access_key = "AWSAccessKey"
aws_secret_key = "AWSSecretKey"
aws_region = "us-west-2"
aws_s3_bucket = "AWS_S3Bucket"
aws_iam_lambda_role = "AWS_IAM_Lambda_Role"
vrlicloud_apikey = "APIKey_vRLICloud"